### ISSUE TITLE
Allow version tags without pre-pending 'v'

### ISSUE THREAD

**Issue by Wavesonics** [TheLartians/CPM.cmake#140] opened 2020-08-09 04:48 UTC
Some repositories don't prepend their tags with **v**x.y.z

But CPM automatically adds the v, so it makes some repositories not work.

**Comment by TheLartians** [comment] 2020-08-10 07:52
Duplicate of #106.

TL;DR use `GIT_TAG` instead of `VERSION` for non `v`-prefixed version tags.

**Closed by TheLartians** 2020-08-10 07:52 UTC
